# fly.toml app configuration file generated for icy-snow-6747 on 2023-08-31T16:11:01-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "icy-snow-6747"
primary_region = "sea"

[build] 

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
